apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replica: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        training: gitops-basic
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: config-volume
          mountPath: /use/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: myapp
